language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
matrix:
  allow_failures:
    - php: 7.1

before_script:
  - travis_retry composer self-update
  # clear composer cache, might speed up finding new tags
  - travis_retry composer clear-cache  
  - composer self-update
  - composer install --no-interaction
  - composer dumpautoload


script:
  - phpunit